apiVersion: apps/v1 
kind: Deployment
metadata:
   name: frontend 
   labels:
     app: frontend 
spec:
   replicas: 3 
   selector:
     matchLabels: 
       app: frontend
   template:
     metadata: 
       labels:
         app: frontend 
     spec:
       containers:
         - name: server
           image: kk74/hipster_shop_frontend:0.0.2
           readinessProbe:
             initialDelaySeconds: 10
             httpGet:
               path: "/_healthz"
               port: 8080
               httpHeaders:
               - name: "Cookie"
                 value: "shop_session-id=x-readiness-probe"
           livenessProbe:
             initialDelaySeconds: 10
             httpGet:
               path: "/_healthz"
               port: 8080
               httpHeaders:
               - name: "Cookie"
                 value: "shop_session-id=x-liveness-probe"
           env:
           - name: PRODUCT_CATALOG_SERVICE_ADDR
             value: localhost
           - name: CURRENCY_SERVICE_ADDR
             value: localhost
           - name: CART_SERVICE_ADDR
             value: localhost
           - name: RECOMMENDATION_SERVICE_ADDR
             value: localhost
           - name: CHECKOUT_SERVICE_ADDR
             value: localhost
           - name: SHIPPING_SERVICE_ADDR
             value: localhost
           - name: AD_SERVICE_ADDR
             value: localhost
